url: https://www.kirbyturner.com
baseurl: 

# Site Settings
title: Kirby Turner
author: Kirby Turner
description: "Kirby Turner is an independent software developer, author, and owner of White Peak Software Inc. Kirby focuses Mac and iOS programming."
keywords: "ios, mac, programming, stowe, vt, vermont, cocoa"

# Career Settings
career-img: "img/career/default.jpg"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: adn
    url: https://alpha.app.net/kirbyt
  - title: twitter
    url: http://twitter.com/kirbyt
  - title: github
    url: http://github.com/kirbyt
  - title: linkedin
    url: http://www.linkedin.com/in/kirbyturner/
  - title: rss
    url: http://www.thecave.com/atom.xml


exclude: ["Rakefile"]
include: [".well-known"]
