url: http://www.kirbyturner.com
baseurl: 

# Site Settings
title: Kirby Turner
description: "Kirby Turner is an independent software developer, author, and owner of Stowe, VT-based White Peak Software Inc. Kirby focuses Mac and iOS programming."
keywords: "ios, mac, programming, stowe, vt, vermont, cocoa, developer, contractor, freelancer"
google-tracking-id: UA-167605-13

# Career Settings
# Default career thumbnail image.
career-img: "img/career/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
